OPTIONAL__command_defaults: {}
OPTIONAL__flow_config:
  REQUIRED__boundary_configs:
  - OPTIONAL__material_zones:
    - TYPE__int|str
    OPTIONAL__outside_zones:
    - TYPE__int|str
    REQUIRED__boundary_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
OPTIONAL__heat_flux_config:
  REQUIRED__boundary_configs:
  - OPTIONAL__material_zones:
    - TYPE__int|str
    OPTIONAL__outside_zones:
    - TYPE__int|str
    REQUIRED__boundary_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
OPTIONAL__hydrostat_config:
  OPTIONAL__sampling_model:
    REQUIRED__kind: TYPE__str
    REQUIRED__params: {}
  REQUIRED__interpolation_model:
    REQUIRED__kind: TYPE__str
    REQUIRED__params: {}
  REQUIRED__pressure_model:
    REQUIRED__kind: TYPE__str
    REQUIRED__params: {}
REQUIRED__files_config:
  OPTIONAL__flow: TYPE__Path
  OPTIONAL__heat_flux: TYPE__Path
  OPTIONAL__initial_conditions: TYPE__Path
  REQUIRED__area: eu_p15un_cold_ft.area
  REQUIRED__check: eu_p15un_cold_ft.chk
  REQUIRED__conductivity: eu_p15un_cold_ft.cond
  REQUIRED__error: eu_p15un_cold_ft.err
  REQUIRED__files: fehmn.files
  REQUIRED__final_conditions: eu_p15un_cold_ft.fin
  REQUIRED__grid: eu_p15un_cold_ft.fehm
  REQUIRED__history: eu_p15un_cold_ft.hist
  REQUIRED__input: eu_p15un_cold_ft.dat
  REQUIRED__material_zone: eu_p15un_cold_ft_material.zone
  REQUIRED__output: eu_p15un_cold_ft.out
  REQUIRED__outside_zone: eu_p15un_cold_ft_outside.zone
  REQUIRED__permeability: eu_p15un_cold_ft.perm
  REQUIRED__pore_pressure: eu_p15un_cold_ft.ppor
  REQUIRED__rock_properties: eu_p15un_cold_ft.rock
  REQUIRED__run_root: eu_p15un_cold_ft
  REQUIRED__storage: eu_p15un_cold_ft.stor
  REQUIRED__water_properties: eu_p15un_cold_ft.wpi
REQUIRED__rock_properties_config:
  REQUIRED__compressibility_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__conductivity_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__grain_density_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__permeability_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__porosity_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__specific_heat_configs:
  - REQUIRED__property_model:
      REQUIRED__kind: TYPE__str
      REQUIRED__params: {}
    REQUIRED__zones:
    - TYPE__int|str
  REQUIRED__zone_assignment_order:
  - TYPE__int|str
