files_config:
  area: p15un_cold_zhf.area
  check: p15un_cold_zhf.chk
  conductivity: p15un_cold_zhf.cond
  error: p15un_cold_zhf.err
  files: fehmn.files
  final_conditions: p15un_cold_zhf.fin
  grid: p15un_cold_zhf.fehm
  heat_flux: p15un_cold_zhf.hflx
  flow: p15un_cold_zhf.flow
  history: p15un_cold_zhf.hist
  input: p15un_cold_zhf.dat
  material_zone: p15un_cold_zhf_material.zone
  output: p15un_cold_zhf.out
  outside_zone: p15un_cold_zhf_outside.zone
  permeability: p15un_cold_zhf.perm
  pore_pressure: p15un_cold_zhf.ppor
  rock_properties: p15un_cold_zhf.rock
  run_root: p15un_cold_zhf
  storage: p15un_cold_zhf.stor
  water_properties: p15un_cold_zhf.wpi

heat_flux_config:
  boundary_configs:
  - boundary_model:
      kind: constant_MW_per_m2
      params:
        constant: 0.0000001 # 10e-7 MW/m2 = 100 mW/m2
    outside_zones: ['bottom']
rock_properties_config:
  compressibility_configs:
  - property_model:
      kind: constant
      params:
        constant: 6.0E-10
    zones: [1, 2, 3]
  conductivity_configs:
  - property_model:
      kind: porosity_weighted
      params:
        rock_conductivity: 2.5
        water_conductivity: 0.62
    zones: [1, 2, 3]
  grain_density_configs:
  - property_model:
      kind: constant
      params:
        constant: 3400
    zones: [1, 2, 3]
  permeability_configs:
  - property_model:
      kind: constant
      params:
        constant: 1.0E-15
    zones: [1, 2, 3]
  porosity_configs:
  - property_model:
      kind: constant
      params:
        constant: 0.1
    zones: [1, 2, 3]
  specific_heat_configs:
  - property_model:
      kind: constant
      params:
        constant: 800
    zones: [1, 2, 3]
  zone_assignment_order: [1, 2, 3]