files_config:
  area: s5_0fr_sm0_p15un_cold.area
  check: s5_0fr_sm0_p15un_cold.chk
  conductivity: s5_0fr_sm0_p15un_cold.cond
  error: s5_0fr_sm0_p15un_cold.err
  files: fehmn.files
  final_conditions: s5_0fr_sm0_p15un_cold.fin
  flow: s5_0fr_sm0_p15un_cold.flow
  grid: s5_0fr_sm0_p15un_cold.fehm
  heat_flux: s5_0fr_sm0_p15un_cold.hflx
  history: s5_0fr_sm0_p15un_cold.hist
  initial_conditions: s5_0fr_sm0_p15un_cold.ini
  input: s5_0fr_sm0_p15un_cold.dat
  material_zone: s5_0fr_sm0_p15un_cold_material.zone
  output: s5_0fr_sm0_p15un_cold.out
  outside_zone: s5_0fr_sm0_p15un_cold_outside.zone
  permeability: s5_0fr_sm0_p15un_cold.perm
  pore_pressure: s5_0fr_sm0_p15un_cold.ppor
  rock_properties: s5_0fr_sm0_p15un_cold.rock
  run_root: s5_0fr_sm0_p15un_cold
  storage: s5_0fr_sm0_p15un_cold.stor
  water_properties: s5_0fr_sm0_p15un_cold.wpi
heat_flux_config:
  boundary_configs:
  - boundary_model:
      kind: constant_MW_per_m2
      params:
        constant: 1.0e-08 # 10 mW/m2
    outside_zones: [bottom]
flow_config:
  boundary_configs:
  - boundary_model:
      kind: 'open_flow'
      params:
        input_fluid_temp_degC: 2
        aiped_to_volume_ratio: 1.0e-08
    outside_zones: ['top']
rock_properties_config:
  compressibility_configs:
  - property_model:
      kind: overburden
      params:
        a: 0.09
        grav: 1.3
        min_overburden: 25
        rhow: 1000
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 6.0E-10
    zones: [2, 3]
  conductivity_configs:
  - property_model:
      kind: porosity_weighted
      params:
        rock_conductivity: 1.5
        water_conductivity: 0.62
    zones: [1]
  - property_model:
      kind: porosity_weighted
      params:
        rock_conductivity: 2.5
        water_conductivity: 0.62
    zones: [2]
  - property_model:
      kind: porosity_weighted
      params:
        rock_conductivity: 3.5
        water_conductivity: 0.62
    zones: [3]    
  grain_density_configs:
  - property_model:
      kind: constant
      params:
        constant: 2650
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 2700
    zones: [2]
  - property_model:
      kind: constant
      params:
        constant: 3400
    zones: [3]
  permeability_configs:
  - property_model:
      kind: constant
      params:
        constant: 1.0E-15
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 1.0E-15
    zones: [2]
  - property_model:
      kind: constant
      params:
        constant: 1.0E-15
    zones: [3]
  porosity_configs:
  - property_model:
      kind: depth_power_law_with_maximum
      params:
        porosity_a: 0.84
        porosity_b: -0.125
    zones: [1]
  - property_model:
      kind: constant
      params:
        constant: 0.1
    zones: [2]
  - property_model:
      kind: constant
      params:
        constant: 0.05
    zones: [3]  
  specific_heat_configs:
  - property_model:
      kind: constant
      params:
        constant: 800
    zones: [1, 2, 3]
  zone_assignment_order: [1, 2, 3]